name: Publish Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7d590

      - name: Setup Java
        uses: actions/setup-java@99b8673ff64fbf33d8d8f9424cc60f1886c51f1d
        with:
          distribution: temurin
          java-version: 24

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@600c74633a7c50c6f1a1c0ec64e18f0ead2db7c5

      - name: Generate Dokka
        run: ./gradlew dokkaGenerate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@0f726310413de48512106d3046821e87224be7e6
        with:
          path: build/dokka/html

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164dcc165de6656944e1dbc0023595037e
